name: SWEP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.4'
    - uses: YakkaDev/mariadb-actions@v1.1.0
      with:
        version: '10.7.3'
        database: 'app_test'
        user: 'root'
        password: 'root'
        root pass: 'root'
    - uses: actions/checkout@v4
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: | 
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        bin/console importmap:install
    - name: validate composer dependencies
      run: composer validate -n
    - name: validate code styles
      run: vendor/bin/php-cs-fixer fix --verbose --dry-run
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        APP_ENV: test
        DATABASE_URL: "mysql://root:root@127.0.0.1:3306/app?serverVersion=10.7.3-MariaDB&charset=utf8mb4"
      run: |
        bin/console d:m:m --no-interaction
        bin/console d:f:l --no-interaction
        vendor/bin/phpunit
